require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.6.0
Style/ConditionalAssignment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/LambdaCall:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: false
Layout/LineLength:
  Enabled: true
  Max: 80
Documentation:
  Enabled: false
